jsf:
  PROJECT_STAGE: Production

  #security:
#  oauth2:
#    client:
#      client-id: 832477315895-e2peuqapckum5mlestdidhce742geeqa.apps.googleusercontent.com
#      client-secret: IYC0Nx6iB9RWcAmkY1iuUbT5
#      scope: profile, email
#      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#      access-token-uri: https://accounts.google.com/o/oauth2/token
#    resource:
#      user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo?alt=json